### ISSUE TITLE
Analyze repository and create Copilot files

### ISSUE THREAD

**Issue by six7** [tokens-studio/graph-engine#699]
We'll assign this issue to Copilot to give it an opportunity to onboard itself to the project.

Include some business explainers on the graph engine, https://documentation.tokens.studio/graph-engine/introduction, I'll add a few sentences at the bottom:

Let's make sure Copilot knows how to work effectively in this repository 🤝 .  This includes ensuring, for each area of the codebase, that:

1. Copilot is able to successfully lint, build and test the code.
2. Copilot understands the existing architecture and coding style.
3. Copilot is given access to the tools and context needed to productively collaborate.

To achieve this, we will make changes in the following:

:gear: Update `.github/workflows/copilot-setup-steps.yaml` to include GitHub Actions steps needed to configure the environment that Copilot will work within.  The steps that Copilot will use should all be part of a single `copilot-setup-steps` job.  If other CI or deployment workflows exist, their environment configuration setup steps can be reused here, but only include steps needed to configure the environment for Copilot.  If not, the tools needed by other build scripts/docs (Makefile, README, package.json, etc.) should be included into `copilot-setup-steps.yaml` steps.  Include environment configuration that requires downloading tools or setting up access to package managers, since Copilot will be unable to do those itself after the `copilot-setup-steps` are executed due to it's network limitations.

🗒 Update `.github/copilot-instructions.md` with key information learned from exploring the repo that will be useful for Copilot to remember for future issues.  Keep this to <250 words, so ensure that only high value information is recorded.  Include details about code style and specific tools that should be used for development in each area of the codebase.  Check out things like READMEs, CONTRIBUTING docs, PR templates and other sources of information about how to work effectively in the repo.

Lastly, as part of doing this work, Copilot should raise any questions or concerns it has around how best to work in the repository, so that the dev team can answer them and help set up Copilot for success :star:.  If Copilot cannot successfully build or test, and does not believe that its updates to `.github/workflows/copilot-setup-steps.yaml` will enable it to, it should raised those as explicit notes for the dev team.  The PR should also request that the dev team ask @copilot to try out the build and test as a comment on the PR so that Copilot has a chance to try the newly added `.github/workflows/copilot-setup-steps.yaml`.

<details>

Example `.github/copilot-setup-steps.md` file:

```yaml
name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for github/setup-goproxy
      contents: read # for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download Go dependencies
        run: go mod download
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: runtime/package-lock.json
      - name: Install runtime dependencies
        working-directory: ./runtime
        run: npm install
```
</details>

Graph Engine business docs (use for context):

```
What’s a Node Editor?
A node editor is a visual tool where you build workflows by connecting nodes—little blocks of functionality—together with edges (lines). Think of it like a flowchart for design logic: each node does something specific (e.g., converts a color to a hex string), and the edges show how data flows between them. In Studio's Graph Engine, this editor lets you create, tweak, and scale design systems without writing code manually. It’s built to be intuitive, combining the visual ease of tools like Figma with the procedural power of something like Blender’s node system. Whether you’re a designer organizing tokens or a design engineer generating outputs for developers, it’s your playground for visual logic.

What Can You Do With It?
The Graph Engine transforms how you manage design systems by letting you define logic visually. Here’s what you can achieve:

Generate Design Tokens Dynamically: Create tokens (e.g., colors, sizes) based on rules, not static lists—like generating a full color scale from a single base color using math and color theory.

Automate Multi-Brand Systems: Switch between brand themes (e.g., Light vs. Dark) instantly by adjusting inputs, perfect for companies managing multiple products.

Scale Complex Designs: Use subgraphs to reuse workflows (e.g., a button styling recipe) across projects, or map arrays to process lists (e.g., converting 10 colors to hex codes at once).

Bridge Design and Code: Output agnostic JSON tokens or even CSS variables that developers can use directly, reducing handoff friction.

Experiment Freely: Test ideas—like creating a type scale with a multiplier—without breaking your system, thanks to non-destructive editing. Example: Imagine you need a color palette for a brand. Start with a base color (#FF5733), use nodes to adjust its lightness for variants (e.g., +10%, -20%), and output a set of hex codes—all in real-time, synced to Figma variables if you want
```
